### ISSUE TITLE
Optional Features - HA not represent the current state

### ISSUE THREAD

**Issue by vampywiz17** [RobHofmann/HomeAssistant-GreeClimateComponent#103]
Hello there,

My Gree climate is support almost all Optional Features, so i add it. We use both HA and EWPE smart app (it easier to manage it for my family). 

So my problem is if i enable a feature (like health mode) in EWPE app, it not set it up in HA. in opposite way of course working.

Any way to read this changes in HA, or it is a tecnical problem and not possible to do this?

**Comment by RobHofmann** [comment]
I think you can read these from the gree protocol. I dont use anything other than HA myself, so I dont run into this. But feel free to make a PR with the changes you need :).

**Comment by vampywiz17** [comment]
@RobHofmann Sorry it represent, only need to wait some time (abou 10 sec). I close this issue.
