### ISSUE TITLE
No quiet fan mode for Toytomi Kuro

### ISSUE THREAD

**Issue by xserk** [RobHofmann/HomeAssistant-GreeClimateComponent#105]
**Describe the bug**
Not sure if this is a bug or not implemented at all. I just started using Home Assistant and there doesnt seem to be a way to enable quiet fan modes (auto quiet and quiet) for Toyotomi Kuro. 

**Platform:**
Synology DSM 6.2.4-25556, Docker, Chrome Version 91.0.4472.124 (Official Build) (64-bit), Home Assistant 2021.6.6

**Comment by RobHofmann** [comment]
My model doesn't make difference betweern "quiet" and "low" fan.

However: feel free to make a PR with the support you need.

**Comment by xserk** [comment]
Actually there are two quiet modes, Quiet (Auto) and Quiet.
