### ISSUE TITLE
Innova HP elec 2.0 support

### ISSUE THREAD

**Issue by bLackCat-79** [RobHofmann/HomeAssistant-GreeClimateComponent#106]
Hi,

It is mentioned that it would support innova. But in reality, the innova HP elec 2.0 is not working!
The gree+ app can't connect to the airco, (port 7000/udp is not used on the airco).

So did anyone had success with innova? Has it been tested?

**Comment by bLackCat-79** [comment]
Ok, I talked with the manufactoror, NO API, NO integration with any kind of platform and NO plans to do it,… it seems its just a crap product.

**Comment by RobHofmann** [comment]
Seems like your type doesn't support the Gree protocol. I'm sorry.
