### ISSUE TITLE
how to add the temperature  sensor

### ISSUE THREAD

**Issue by crathyd** [RobHofmann/HomeAssistant-GreeClimateComponent#12]
i have a temperature sensor by broadlink and want to appear it into the climate temperature graph;
but i put the temperature_sensor command into the py file.....
error ........

could U add the Temp Sensor into the  Py?

**Comment by RobHofmann** [comment]
Hi! I'm not sure if this is possible. Personally I solved this by using different components on my overview.

Take a look [here](https://imgur.com/8KOX4E3)

For the Thermostat i used [this component](https://github.com/ciotlosm/custom-lovelace/tree/master/thermostat-card)
For the Graphs i used [this component](https://github.com/kalkih/mini-graph-card)

PS. Sorry for the orange glow. This is flux not really working with Windows 1903 ¯\_(ツ)_/¯

Let me know what you think.

**Comment by crathyd** [comment]
i just want the real temp appeared on the temperature graph, when i click the air-condition button there is a temperature graph on the window but there is only one line on it about the seeting temp,i want there can show two lines for real temp and setting temp.....

**Comment by crathyd** [comment]
https://bbs.hassbian.com/forum.php?mod=viewthread&tid=2273&highlight=%E7%A9%BA%E8%B0%83

like this

**Comment by RobHofmann** [comment]
Feel free to create a pullrequest with the changes you need :).

**Comment by crathyd** [comment]
thanks very much ^_^

**Comment by RobHofmann** [comment]
This should be fixed by adding this to your climate config:

temp_sensor: <temperature sensor to use for current temp>

Can you confirm this?

PS. Take a look at the readme for a full example.

**Comment by crathyd** [comment]
i tested the file but there's some error like these
Your configuration contains extra keys that the platform does not support (but were silently accepted before 0.88). Please find and remove the following.This will become a breaking change.

[min_temp], [max_temp], [target_temp]. (See /config/configuration.yaml, line 691).
Offending data: {"platform": "gree", "name": "ciwokongtiao", "host": "<redacted>", "port": "<redacted>", "mac": "<redacted>", "temp_sensor": "<redacted>", "min_temp": 16, "max_temp": 30, "target_temp": 20, "target_temp_step": "<redacted>"}

**Comment by RobHofmann** [comment]
Sorry there has been an update. Please remove those lines from config:
     min_temp: 16
     max_temp: 30
     target_temp: 21

This will get rid of the error. I just confirmed that the temperature sensor is working for me.

Please let me know! :)

**Comment by RobHofmann** [comment]
I'm going to close this for now. Let me know if you need anymore help or if it is not working.

**Comment by crathyd** [comment]
it's working very well now ~~~ thank U very much  o(∩_∩)o
