### ISSUE TITLE
Ifeel mode

### ISSUE THREAD

**Issue by drynish** [RobHofmann/HomeAssistant-GreeClimateComponent#124]
There's a mode that is available on my remote control for my gree extreme split heat pump. The mode named ifeel, makes the remote the sensor for the temperature. This way, I can place the remote in a more center zone of the house. The heat pump is also working longer since it's not considering the temperature in the same zone where it's installed.

I would like to add a binary sensor to activate this mode like the actual x-fan, health or light.

**Comment by NicolasLM** [comment]
As far as I know this is not possible through the API, the only way to activate ifeel and send temperature is through the IR interface. Some people use an Arduino that pretends to be the remote to control ifeel without actually using the remote.

**Comment by ronnieSVK** [comment]
Can we something do, in order to help with this request ?

Im also struggling with this option and it would be gamechanger...
There isnt option to (at least) TURN ON "I Feel Mode" and measure the temperature from ACs Remote Controller instead of its bulit in sensor via integration.

Thank you !

**Comment by RobHofmann** [comment]
Feel free to create a PR for this. I'm closing this for now because its not in the current scope.
