### ISSUE TITLE
launch climate.yalm

### ISSUE THREAD

**Issue by UVivarelli** [RobHofmann/HomeAssistant-GreeClimateComponent#130]
**Describe the bug**
When I try to reboot HA, I've this error:

The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: in "/config/configuration.yaml", line 26, column 10: Unable to read file /config/climate.yaml.

**Configuration**
Share your YAML here

file climate.yalm

- platform: gree
  name: First AC
  host: 192.168.1.80
  port: 7000
  mac: 50:2C:C6:3E:52:0E
  target_temp_step: 1

I've put on line 26 of configuration.yalm this:
climate: !include climate.yaml

**Platform:**
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

Browser: Chrome Versione 104.0.5112.101 (Build ufficiale) (x86_64)

**Comment by RobHofmann** [comment]
It can't find the climate.yaml file. Are you sure its in the correct place? Also; does it have the correct file permissions?

**Comment by UVivarelli** [comment]
![Schermata 2022-09-03 alle 07 38 33](https://user-images.githubusercontent.com/104590049/188257493-2599bed6-41ef-47a5-bc14-d730ff294535.png)

I think position is correct, see attach. Hoc can I modify the permission of climate.yalm file? I've created it in Studio Core Server as new file

**Comment by RobHofmann** [comment]
Ah your file is called climate.yalm, where it should be named climate.yaml. See if that fixes the issue.

**Comment by UVivarelli** [comment]
> Ah your file is called climate.yalm, where it should be named climate.yaml. See if that fixes the issue.

noooo!!! I'm a stupid!!

ok this i resolved! but... second step: why I can't find the service or the entity?
![Schermata 2022-09-03 alle 07 38 33](https://user-images.githubusercontent.com/104590049/188272482-257cd1db-6f9e-41aa-b3ed-cb3db0874aa4.png)

**Comment by UVivarelli** [comment]
noooo!!! I'm a stupid!! thank you!

ok this is resolved! but... second step: why I can't find the service or the entity?

where can I check if all is OK?

**Comment by UVivarelli** [comment]
![Schermata 2022-09-03 alle 17 17 17](https://user-images.githubusercontent.com/104590049/188277060-9fec6e2b-5f7d-4419-9277-22dbba6f1273.png)
![Schermata 2022-09-03 alle 17 17 39](https://user-images.githubusercontent.com/104590049/188277067-b044338b-9c2b-4433-82bd-6d00bfb5cc1b.png)

**Comment by UVivarelli** [comment]
Ok! I've found the entity!! Thanks!
