### ISSUE TITLE
Operation Mode

### ISSUE THREAD

**Issue by TheAmitMa** [RobHofmann/HomeAssistant-GreeClimateComponent#14]
Hi.
While in other climate components the operation mode list the power state (on/off), in this component we get the operation state (cool/heat/etc).

The result is that the component cannot powered on/off from the lovelace thermostat card.

example from other climate component (detailes from entity attributes):

fan_list: low,mid,high,auto
**operation_mode: off**
operation_list: off,cool,heat

and example from gree component:

fan_list: auto,Low,Medium-Low,Medium,Medium-High,High,Turbo,Quiet
**operation_mode: cool**
operation_list: auto,cool,dry,fan_only,heat

Thanks!

**Comment by RobHofmann** [comment]
Please review Pull Request #15. This should do the trick. Let me know if you agree with the solution.

**Comment by TheAmitMa** [comment]
Thanks.
It's seems that the climate card now works as expected, but there is a bug now with the operation mode: while the AC actual mode is "cool", the component shows the mode as "auto". switching to "cool" and the AC actual mode is set to "dry". ""dry" to "fan". "fan" to "heat" and "heat" to "auto".

**Comment by RobHofmann** [comment]
Please check it now. I've moved it down the list (i'm using the positions of items in the list. when i added the "State Off" in as the first item, everything got moved). I just checked it with my own AC. Seems to work now. Let me know.

**Comment by TheAmitMa** [comment]
Looks good.
Thanks.
