### ISSUE TITLE
External temp sensor not showing temp

### ISSUE THREAD

**Issue by Hugo0485** [RobHofmann/HomeAssistant-GreeClimateComponent#140]
Since last update my external temp sensor is not showing any data. When i revert back to version 2.3.2 the temp is shown again

Thanks for creating this addon, i really appreciate it!

After HAOS 2023.6 the old version does not work any more, so i switched to the newer version of this addon without the temperature sensor. Hopefully you will find a solution to this, if i can test something; let me know!

![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/39700152/deba66a4-243b-4e4b-8cac-b78d4747cec8)

- platform: gree
  name: Airco boven
  host: 10.10.11.13
  port: 7000
  mac: f4:91:1e:31:63:41
  target_temp_step: 1
#  encryption_key: <OPTIONAL: custom encryption key>
#  uid: <some kind of device identifier. NOTE: for some devices this is optional>
  temp_sensor: sensor.temperatuur_sensor_slaapkamer_temperature
  lights: input_boolean.first_ac_lights
  xfan: input_boolean.first_ac_powersave

**Comment by onezerodan** [comment]
+1. Also facing this problem.

**Comment by maymaymay** [comment]
+1, same here.

**Comment by RobHofmann** [comment]
Hmm thats interesting. I hope someone who has this setup can check it and make PR for this.

For everyone facing this issue and downgrading to the previous version; know that in the next HA release (2023.6) the old version will stop working due to Python being upgraded to 3.11.

**Comment by codo70** [comment]
+1, external sensor does not work. Same Here

**Comment by smarecki** [comment]
Same issue. External temp sensor is not showing any value. Reverted to previous version, everything works. In HA release (2023.6) the old version will stops working.

**Comment by RobHofmann** [comment]
Should be fixed with 2.4.1.

Let me know.

**Comment by Hugo0485** [comment]
Can confirm, problem is fixed! Thank you for updating so fast!

**Comment by maymaymay** [comment]
It's working again. Thank YOU!
