### ISSUE TITLE
Wrong product

### ISSUE THREAD

**Issue by Monacoslo** [RobHofmann/HomeAssistant-GreeClimateComponent#149]
I have Gree+ dehumidfier, it is shown in the HA, but instead of having the posibility to turn it on or off and set humidity, I see the items that do not do anything. Only ambiental temperature is correct
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/47989822/9250f9d2-b520-49b1-a5b9-56918cf25f52)
![Screenshot_20231201-135259](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/47989822/b83fb2c2-35f3-4019-995e-5e93930c9125)

**Comment by RobHofmann** [comment]
Feel free to add support for this. This is however not the current scope of this component, so i'm closing this one.
