### ISSUE TITLE
Turning on Gree air conditioner after starting Home Assistant

### ISSUE THREAD

**Issue by odis68** [RobHofmann/HomeAssistant-GreeClimateComponent#160]
**Describe the bug**

If Home Assistant has been launched before the device, an error occurs
It was not possible to call the Climate/set_temperature service. Expected Float for Dictionary Value @ Data ['Temperature']

**To Reproduce**
1. If Home Assistant has been launched before the device, an error occurs
2. ''
3. ''
4. It was not possible to call the Climate/set_temperature service. Expected Float for Dictionary Value @ Data ['Temperature']

**Configuration**
- platform: gree
  name: Gree AC1
  host: 192.168.22.**
  port: 7000
  mac: 'f4:91:1e:**:**:**'
  target_temp_step: 1
  timeout: 5
  xfan: input_boolean.gree_ac_1_xfan    #xfan: <OPTIONAL: input_boolean to switch AC xfan mode on/off. For example: input_boolean.first_ac_xfan>
  sleep: input_boolean.gree_ac_1_sleep   #<OPTIONAL: input_boolean to switch AC sleep mode on/off. For example: input_boolean.first_ac_sleep>
  lights: input_boolean.gree_ac_1_lights
  powersave: input_boolean.gree_ac_1_powersave  #<OPTIONAL: input_boolean to switch AC powersave mode on/off. For example: input_boolean.first_ac_powersave>
  health: input_boolean.gree_ac_1_plasma  # <OPTIONAL: input_boolean used to switch the Health option on/off of your first AC. For example: input_boolean.first_ac_health>
  temp_sensor: input_number.gree_ac1_currenttemperature

**Expected behavior**
After turning on Gree, gain access without restarting Home AssistSnt itself - or recommendations for commanding commands with GREE.

**Screenshots**

**Platform:**
 - OS: Home Assistant OS 12.3
 - Version [The last version]

**Additional context**
The integration of the Node-Red itself picks up the inclined air conditioner and controls it. This integration is only after restarting Home Assistant

**Logs**
I do not find records about this event

**Comment by odis68** [comment]
Sorry I didn't see your comment
[https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/113#issuecomment-2107054398](url)

**Comment by toughvj** [comment]
I'll have to take a look at this. I think I have a solution for this without using it config_flow

**Comment by toughvj** [comment]
Solved in latest PR. Waiting for @RobHofmann  approval.

**Comment by odis68** [comment]
Thanks for your work!!!!

**Comment by toughvj** [comment]
solved with PR #179, can be closed
