### ISSUE TITLE
Devices unavailable

### ISSUE THREAD

**Issue by trebestie** [RobHofmann/HomeAssistant-GreeClimateComponent#161]
**Describe the bug**
After last upgrade devices are unavailable 

**Expected behavior**
Devices available

**Platform:**
Home assistant core 2024.2.2

**Logs**
I'm getting following error.
Do I need python 3.12?

> Platform error 'climate' from integration 'gree' - cannot import name 'EventStateChangedData' from 'homeassistant.core' (/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py)
> Platform error 'climate' from integration 'gree' - cannot import name 'EventStateChangedData' from 'homeassistant.core' (/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py)
> Platform error 'climate' from integration 'gree' - cannot import name 'EventStateChangedData' from 'homeassistant.core' (/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py)

My regards

**Comment by kagiedrius** [comment]
I have the same issue after the latest update

**Comment by RobHofmann** [comment]
Update your Home Assistant or downgrade the gree component. This component version is compatible with newer hass versions.
