### ISSUE TITLE
Can you support the `Anti Direct Blowing Wind Shield` feature

### ISSUE THREAD

**Issue by red3** [RobHofmann/HomeAssistant-GreeClimateComponent#162]
My gree air conditioner has a feature called  `Anti Direct Blowing Wind Shield`, which is to prevent the cold wind blowing directly on people, I can control it by the Gree+ app. 
Can you support this feature?
or if there a way to keep the previous status of this so called  `Anti Direct Blowing Wind Shield`, cause every time I turn on this feature using the Gree+ app, and next time turn on the air conditioner using home assistant, the status of this feature just gone. 

Thanks for your work.

**Comment by toughvj** [comment]
Can you provide device model?

**Comment by red3** [comment]
@toughvj How can I find the device model? On the Gree+ app, it displayed as 云轩(it’s a Chinese name and I don’t know corresponding English version)

**Comment by toughvj** [comment]
Should be located somewhere on unit.

**Comment by red3** [comment]
Does it begin with KFR-xxx(some numbers and alphabets)

**Comment by red3** [comment]
It’s KFR-35GNhHc1BAt

**Comment by toughvj** [comment]
This is Gree unit?

**Comment by red3** [comment]
yeah, why asking (I am not sure it’s a global or Chinese only)

**Comment by toughvj** [comment]
Does it looks like U Crown series?

**Comment by red3** [comment]
I just googled the U Crown series and Yeah it looks like U Crown series.

**Comment by red3** [comment]
the rectangular unit is placed  high up on the wall , so the cold air from the ac might blow directly on people. Therefore, this unit comes with this feature.

**Comment by toughvj** [comment]
Have you tried to achieve this effect by setting some od fixed horizontal swing position?

**Comment by red3** [comment]
I'll try it later to see if this meet my needs

**Comment by red3** [comment]
@toughvj after extract Gree+'s app data, I can see the unit support those commands:
`["SetTem","Add0.5","TemRec","Mod","functype","WdSpd","Tur","Quiet","SwUpDn","SmartWind","SwingLfRig","Health","Lig","LigSen","AntiDirectBlow","UnmanedShutDown","SwhSlp","SlpMod","AppTimer","Pow","AssHt","TemSen"]`, and there was a command called **AntiDirectBlow**,
and the status of AntiDirectBlow would looks like: `{"AntiDirectBlow":1}` or `{"AntiDirectBlow":0}`, 1 means open and 0 means off.

**Comment by toughvj** [comment]
You can try with attached file. Remember to add input_boolean helper and then add it to configuration of unit:
anti_direct_blow: input_boolean. with given name
[climate.txt](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/15394506/climate.txt)

please give any feedback.

**Comment by red3** [comment]
Thanks for your help, I’ll try it later this week and will let you know if it works.

**Comment by red3** [comment]
@toughvj it seemed that the attached file miss the {AntiDirectBlow}  value of “p” para on line 320, it works well after correct this.
I’m so glad you made this happen, will you consider publishing this?

**Comment by toughvj** [comment]
yes, I found this bug yesterday. This feature is in latest PR. waiting for @RobHofmann

**Comment by red3** [comment]
👍Can’t wait to see this.

**Comment by toughvj** [comment]
@red3 can U try attached file, if this is working or throw any errors?
[climate.txt](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/15456006/climate.txt)

**Comment by red3** [comment]
I’ll try this tomorrow, this version makes any changes?

**Comment by toughvj** [comment]
yes, it changes the way a device is added to HA even if it is unplugged when HA starts. Rob reports errors and it works fine for me.

**Comment by red3** [comment]
it's working fine on my side, and I can see the following logs:
available(): Device is online

**Comment by toughvj** [comment]
solved with PR #179, can be closed
