### ISSUE TITLE
getting error :  2024-05-29 08:57:25.609 ERROR (MainThread) [homeassistant.components.climate] Setup of platform gree is taking longer than 60 seconds. Startup will proceed without waiting any longer.

### ISSUE THREAD

**Issue by mulera84** [RobHofmann/HomeAssistant-GreeClimateComponent#170]
**Describe the bug**
After I add the configs to climate.yaml and restart the HA ( container with network in HOST mode) 
I am getting error and AC ( Tadiran alpha pro 10 ) is not added ( on its own app it works fine ) 

**To Reproduce**
just configuring and restart HA

**Configuration**
climate.yaml
- platform: gree
  name: MAMAD AC
  host: 10.100.102.8
  port: 7000
  mac: 94:24:b8:a1:68:f5
  target_temp_step: 1
  lights: input_boolean.MAMAD_AC_lights
  xfan: input_boolean.MAMAD_AC_xfan
  health: input_boolean.MAMAD_AC_health
  sleep: input_boolean.MAMAD_AC_sleep
  powersave: input_boolean.MAMAD_AC_powersave
  eightdegheat: input_boolean.MAMAD_AC_8degreeheat
  air: input_boolean.MAMAD_AC_airscavenging

LOG :
2024-05-29 08:57:15.595 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2024-05-29 08:57:15.595 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2024-05-29 08:57:15.595 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2024-05-29 08:57:15.596 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2024-05-29 08:57:15.600 INFO (MainThread) [custom_components.gree.climate] Fetching(10.100.102.8, 7000, 10, {"cid": "app","i": 1,"pack": "[OMMITED- there is a key]","t":"pack","tcid":"9424b8a168f5","uid": 0})
2024-05-29 08:57:25.609 ERROR (MainThread) [homeassistant.components.climate] Setup of platform gree is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Platform:**
 - OS:  debian running Docker - HA 
   Core    2024.5.4
   Frontend 20240501.1

**Comment by jodewee** [comment]
maybe you should try the new encryption version?
I had to also fill in the mac adress like this:

  - platform: gree
    name: GREE_AC_Lander
    host: 192.168.3.53
    port: 7000
    target_temp_step: 1
    mac: "502cc63feb0d"
    encryption_version: 2
    uid: 0    
    health: input_boolean.ac_Lander_ionisatie
    xfan: input_boolean.ac_Lander_xfan
    lights: input_boolean.ac_Lander_light
    sleep: input_boolean.ac_Lander_sleep
    temp_sensor: sensor.temp_jelle_temperature

**Comment by mulera84** [comment]
Thanks,
How to get the new version with the new encryption?
Its a Tadiran alpha pro 10 AC 

I tryied the preinstalled version in yhe integrations 
I saw in the logs that mac was sent as you described 
But the same thing
The AC Is being discovered but after few seconds is unavailable

**Comment by jodewee** [comment]
just use the latest version of the repository.
and be sure to use this in the yaml (like described above)

encryption_version: 2

**Comment by mulera84** [comment]
Hi, Thanks the logs looks much better 
after changing to version 2 and mac as you described 

Now I can see the AC in entities list 
Thanks

**Comment by xertux** [comment]
WOW!! This actually solved my problem to connect my Vaillant VAIL1-030WNI A/C to home assistant.

This is my setup now. I hope it helps someone.

climate:
  - platform: gree
    name: Vaillant
    host: 192.168.1.27
    port: 7000
    mac: "502cc65608b3"
    encryption_version: 2
    uid: 0
    lights: input_boolean.vaillant_lights
    xfan: input_boolean.vaillant_xfan
    health: input_boolean.vaillant_health
    sleep: input_boolean.vaillant_sleep
    powersave: input_boolean.vaillant_powersave

    
input_boolean:    
  vaillant_lights:
    name: "Lights Vaillant"
  vaillant_xfan:
    name: "xfan Vaillant"
  vaillant_health:
    name: "Health Vaillant"
  vaillant_sleep:
    name: "Sleep Vaillant"
  vaillant_powersave:
    name: "Power Save Vaillant"

**Comment by RobHofmann** [comment]
Glad to see you guys resolved the issues. Feel free to reopen if you still experience issues.
