### ISSUE TITLE
Does not work with latest Cooper&Hunter Smart Wi-Fi devices

### ISSUE THREAD

**Issue by Darknet-11** [RobHofmann/HomeAssistant-GreeClimateComponent#173]
Spent days trying to make this work with two new C&H mini splits that us the US-OSK103 Wi-Fi adapter.  Packet capture shows the C&H app sends UDP broadcasts on port 6445, not 7000.  Tried manually changing the climate.yaml to use port 6445 but no luck.  Further research indicated that some Midea units use an "OSK103" Wi-Fi adapter.  Tried the "Midea Smart AC" integration available via HACS which doesn't mention Cooper&Hunter at all, and that actually worked great.

So, I think it would be prudent to make mention in the Readme that new Cooper&Hunter mini splits that use the US-OSK103 Smart Wi-Fi adapters are apparently based on Midea and not compatible with this Gree integration.

**Comment by RobHofmann** [comment]
This is why we try to also list the model number. It's impossible to list all the things that don't work :).

Thanks for the heads up though!
