### ISSUE TITLE
Failed to connect to AC

### ISSUE THREAD

**Issue by piotrszpruta** [RobHofmann/HomeAssistant-GreeClimateComponent#176]
I'm configuring Gree AC with this component, I get IP and Mac address of the unit and insert it in configuration.yaml. After restarting I see the entity but in logs I've received such information:
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/38475451/d0a908dc-d114-474c-acd0-9cb8ea40bf68)

**To Reproduce**
1. Configure integration
2. Check logs

**Configuration**
- platform: gree
  name: Climate
  host: 192.168xxxx
  port: 7000
  mac: "94:24:xxxxx"
  target_temp_step: 1
  encryption_version: 1

**Expected behavior""
Climate connected.

**Platform:**
 - OS: HAOS
 - Browser chrome
 - Version 12.4

**Comment by Tempmail1234-pass** [comment]
@piotrszpruta Maybe this can help you https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/174#issuecomment-2178157325

**Comment by toughvj** [comment]
solved with PR #179, can be closed
