### ISSUE TITLE
Since upgrade to 2.12.0 Lost Climate present mode (Vertical swing mode) (EMPTY)

### ISSUE THREAD

**Issue by sthevenp** [RobHofmann/HomeAssistant-GreeClimateComponent#177]
**Describe the bug**
Since upgrade to 2.12 Lost Vertical Switch settings from GUI

**To Reproduce**
The Vertical swing mode shows empty in the Climate settings

**Configuration**
Standard

**Expected behavior**
Before I upgrade to 2.12 the Vertical swing mode was able to adjust from the GUI - now its gone

**Screenshots**
See the bottom of the attached picture!!!
![IMG_0041](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/30027604/9c5c3ff6-db03-4be6-843e-26727105cfe4)

**Platform:**
 - OS: 12.4, Core: 2024.6.3, Supervisior: 2024.06.00 FrontEnd: 20240610.1
 - Browser Safari/Chrome iPAD App
 - Version 

**Additional context**

**Logs**
2024-06-19 08:53:24.479 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139803016358800] Preset mode is not valid. Valid preset modes are:

**Comment by jodewee** [comment]
which encryption method do you use?

**Comment by alanoitaliano** [comment]
Same here after update, when re-added the entity vertical swing is just not there anymore

**Comment by ShiinaKin** [comment]
try to append `horizontal_swing: true` in climate.yml, my a/c support horizontal swing

for me, the panel look like now in 2.12

![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/52254895/9e0ab13d-16a3-4507-90bb-1a00ddcb4f14)

**Comment by sthevenp** [comment]
> try to append `horizontal_swing: true` in climate.yml, my a/c support horizontal swing
> 
> for me, the panel look like now in 2.12, HA webui
> 
> ![image](https://private-user-images.githubusercontent.com/52254895/341010308-9e0ab13d-16a3-4507-90bb-1a00ddcb4f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTAzMDIsIm5iZiI6MTcxODc5MDAwMiwicGF0aCI6Ii81MjI1NDg5NS8zNDEwMTAzMDgtOWUwYWIxM2QtMTZhMy00NTA3LTkwYmItMWEwMGRkY2I0ZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA5NDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWM5YWYwN2NlMDk1ZWY5ZGVjYzJkOGFkNDA2NjViODMwNWU2NjA2M2RkMWVjNWJhNjkxNmM4YmU5ZmRjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wp1cNgWa0m-2aYDePNbvSvy5rxlFlTJmNeholqmKrRE)

It worked.

![IMG_0044](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/30027604/03c35836-8a6f-4de2-a38b-d0ccc6087eb6)


Added this line under all climates and now it is working fine: 

horizontal_swing: true

Thx for the hint!

**Comment by Tempmail1234-pass** [comment]
@ShiinaKin @sthevenp Do you know how to set the A/C light from the panel? This is the 'Lig' option.
From where the html code for the panel is taken? How can I change it?

**Comment by jodewee** [comment]
> @ShiinaKin @sthevenp Do you know how to set the A/C light from the panel? This is the 'Lig' option. From where the html code for the panel is taken? How can I change it?

create a toggle helper & configure that in the climate.yaml config:

  - platform: gree
    name: GREE_AC_Slaapkamer
    host: 192.168.2.108
    port: 7000
    target_temp_step: 1
    mac: "50:2c:c6:6c:d3:63"
    encryption_version: 2
    timeout: 60
    health: input_boolean.ac_slaapkamer_ionisatie
    xfan: input_boolean.ac_slaapkamer_xfan
    lights: input_boolean.ac_slaapkamer_light
    sleep: input_boolean.ac_slaapkamer_sleep
    temp_sensor: sensor.temp_slaapkamer_temperature

**Comment by Tempmail1234-pass** [comment]
@jodewee What is a toggle helper? and how to configure the string after `input_boolean` correctly if my A/C name is just `ac`? What to write there?

**Comment by jodewee** [comment]
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/40162805/7b947868-3dae-4861-b459-822534e751a8)
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/40162805/d06bc61e-8f64-45cf-a5a2-bd2e397d2f9e)
![image](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/assets/40162805/004a58cd-1c36-4712-b831-4e8e84a4fac5)

**Comment by toughvj** [comment]
@RobHofmann plea close as resolved.
