### ISSUE TITLE
error in the message

### ISSUE THREAD

**Issue by crathyd** [RobHofmann/HomeAssistant-GreeClimateComponent#18]
Log Details (WARNING)
Mon Jun 10 2019 23:08:34 GMT+0800 (CST)

Updating state for climate.zhuwokongtiao (<class 'custom_components.gree.climate.GreeClimate'>) took 0.411 seconds. Please report platform to the developers at https://goo.gl/Nvioub

**Comment by RobHofmann** [comment]
Similar to #17 

Haven't found a fix yet. Any info is welcome.

**Comment by RobHofmann** [comment]
Closing this as it is similar to #17
