### ISSUE TITLE
Cannot connect but previously worked before AC FW upgrade

### ISSUE THREAD

**Issue by vantech14** [RobHofmann/HomeAssistant-GreeClimateComponent#193]
Hi, 

Previously this integration worked, then i upgraded my Gree ACs to FW version v1.23. After this, the integration has stopped working. 

I can ping the ACs and there are no firewall issues. Here is my config: 

  - platform: gree
    name: Master Bedroom AC
    host: 192.168.12.19
    port: 7000
    mac: '94:24:B8:XX:XX:XX'
    target_temp_step: 1
    horizontal_swing: true
    lights: input_boolean.mb_ac_light

The climate entities just show "unavaliable". 

Using latest version of integration 2.14.0 (tried older versions also). I can confirm port 7000 is open, but interestingly, even a similar nodered integration fails to connect. I have tried 3x ACs all are behaving the same way. 

Any ideas?

Thanks.

**Comment by toughvj** [comment]
if I'm not mistaken, FW 1.23 requires encryption version: 2 in the configuration.

**Comment by vantech14** [comment]
@toughvj this is what I am struggling to get. The ACs were joined to the Gree app using an iPhone.

How can I get the v2 encryption key? I can't find any documentation. 

Thanks.

**Comment by toughvj** [comment]
You don't need encryption key. Set encryption_version: 2 in config and that's all.

**Comment by vantech14** [comment]
> You don't need encryption key. Set encryption_version: 2 in config and that's all. 

@toughvj this worked! Thank you very much!!

**Comment by toughvj** [comment]
You're welcome ;) please close as solved.
