### ISSUE TITLE
How to check in codition state of AC?

### ISSUE THREAD

**Issue by majker17** [RobHofmann/HomeAssistant-GreeClimateComponent#199]
Dears,

I spend some time to checking in Automatization HVAC mode or the state of AC (is off or on) but without any results. Please tell me what I did write wrong in my code?

condition: state
entity_id: climate.pokoj_105
state: "'on'"
attribute: hvac-modes_

My goal is to check what is the state of AC - if it is off please set some paraemters.

**Comment by majker17** [comment]
Hello anyone help? I will be appreciated for the support.

**Comment by RobHofmann** [comment]
Can you share the full automation?

**Comment by majker17** [comment]
alias: I_piętro_pokoj_105_ON
description: ""
trigger:
  - platform: time_pattern
    seconds: "1"
condition:
  - condition: time
    after: "07:30:00"
    before: "17:00:00"
  - condition: state
    entity_id: calendar.polska
    state: "off"
  - condition: state
    entity_id: climate.pokoj_105
    attribute: hvac_mode
    state: cool
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: climate.pokoj_105
            attribute: current_temperature
            above: 0
            below: 22
          - condition: template
            value_template: "{{ now().month in [1,2,3,11,12] }}"
        sequence:
          - service: climate.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: climate.pokoj_105
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: heat
            target:
              entity_id: climate.pokoj_105
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 22
              hvac_mode: heat
            target:
              entity_id: climate.pokoj_105
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: climate.set_fan_mode
            metadata: {}
            data:
              fan_mode: Low
            target:
              entity_id: climate.pokoj_105
      - conditions:
          - condition: numeric_state
            entity_id: climate.pokoj_105
            attribute: current_temperature
            above: 22
          - condition: template
            value_template: "{{ now().month in [1,2,3,11,12] }}"
          - condition: state
            entity_id: climate.pokoj_105
            attribute: hvac mode()
            state: heat
        sequence:
          - service: climate.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: climate.pokoj_105
      - conditions:
          - condition: numeric_state
            entity_id: climate.pokoj_105
            attribute: current_temperature
            above: 24
          - condition: template
            value_template: "{{ now().month in [4,5,6,7,8,9,10] }}"
          - condition: state
            entity_id: climate.pokoj_105
            attribute: hvac_mode
            state: "OFF"
        sequence:
          - service: climate.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: climate.pokoj_105
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: cool
            target:
              entity_id: climate.pokoj_105
          - service: climate.set_temperature
            metadata: {}
            data:
              temperature: 23
              hvac_mode: cool
            target:
              entity_id: climate.pokoj_105
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - service: climate.set_fan_mode
            metadata: {}
            data:
              fan_mode: Low
            target:
              entity_id: climate.pokoj_105
      - conditions:
          - condition: numeric_state
            entity_id: climate.pokoj_105
            attribute: current_temperature
            below: 23
            above: -0.1
          - condition: template
            value_template: "{{ now().month in [4,5,6,7,8,9,10] }}"
        sequence:
          - service: climate.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: climate.pokoj_105
mode: single

**Comment by RobHofmann** [comment]
I think you need to remove the `attribute: hvac_mode`

So something like
```yaml
- condition: state
  entity_id: climate.pokoj_105
  state: heat
```

**Comment by majker17** [comment]
Thank you - I will check and give the feedback.

**Comment by majker17** [comment]
Thank you - everything works fine so I will close the topic.

In this case I need to read status.
