### ISSUE TITLE
Air Conditioner State

### ISSUE THREAD

**Issue by TheAmitMa** [RobHofmann/HomeAssistant-GreeClimateComponent#20]
Hi.
In this component, the state of the ac's is on/off. 
In different climates entities, the state is off/cool/heat/etc...
This reflected at the lovelace climate card. The ac's seems turned on at first look (even though the state display is shows 'off', but the card is painted in color like it turned on).

Thanks!

**Comment by RobHofmann** [comment]
I should be able to fix this. Currently my own Home Assistant environment is broken, so i'll fix it when i get it back up and running. (SD Card broke :()

**Comment by TheAmitMa** [comment]
Any updates?

**Comment by RobHofmann** [comment]
I'm sorry. I have very little time at the moment. Feel free to create a PR with your needed changes.

**Comment by RobHofmann** [comment]
I will delay this until 0.96 comes out. The climate component is redone in that version.

**Comment by RobHofmann** [comment]
I've just taken a look at this. I've created a branch with the needed change. Can you confirm this is what you had in mind?:
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/tree/operation_state

Let me know!

**Comment by TheAmitMa** [comment]
Looks Good!
Thanks!
