### ISSUE TITLE
New HA 0.96 climate integration

### ISSUE THREAD

**Issue by omribenami** [RobHofmann/HomeAssistant-GreeClimateComponent#23]
Hi Rob.
Do you know if  the new climate integration on 0.96 will ruine the component?

https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html?fbclid=IwAR3SG6yOtZQR_kkoOObUupeEqN-jdbVUPHJkOci_De8yuiWL4OlUCvJ9bAw

**Comment by RobHofmann** [comment]
Hey from what i can see we need to make a few changes. I'll probably hit this upgrading when 0.96 comes out and will fix it (since i use my AC a lot ;))

**Comment by omribenami** [comment]
And since their a whole community that counts on you 😉🙏. I use it a lot as well. Thanks!!

**Comment by RobHofmann** [comment]
Alright, i've taken a look at the beta. I've created a branch with the needed changes. For now it works in the 0.96 beta 1. Would you be so kind to give it a go and test it as well?

Please see this branch: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/tree/newclimatecomponent

**Comment by omribenami** [comment]
Hi Rob.
Ive seen your massage. Ill give it a go in a few days (im out of town at the moment).
Thanks for the hard work 🙏 ill let you know as soon as i can 👍👍

**Comment by RobHofmann** [comment]
Tomorrow i’ll bw pushing this to master as 0.96 comes out tomorrow.

**Comment by Idanit** [comment]
With 0.96 got "Platform not found: climate.gree". So I,ve replaced climate.py with the one above and it helpes... but, I've lost now all the control icons in custom:simple-thermostat card. With the standard thermostat card everything works fine.
![AwesomeScreenshot-Home-Assistant-2019-07-18-07-07-66](https://user-images.githubusercontent.com/52539029/61432429-c29b6900-a930-11e9-8a56-c1b18e414143.png)
![AwesomeScreenshot-Home-Assistant-2019-07-18-07-07-16](https://user-images.githubusercontent.com/52539029/61432449-d34bdf00-a930-11e9-88f4-1815b31a9b73.png)

**Comment by RobHofmann** [comment]
The climate platform has been transformed. I dont have an overview of the full changes yet, but afaik some features have been removed.

Also, maybe the lovelace card has to be updated?

**Comment by RobHofmann** [comment]
Closing this issue. Support for HASS 0.96 has been release in the 2.0 release. @Idanit if you need more help with your specific issue, please open a new issue for this.

**Comment by omribenami** [comment]
works like a charm rob! thanks!!
