### ISSUE TITLE
Health option

### ISSUE THREAD

**Issue by dragonflyuk** [RobHofmann/HomeAssistant-GreeClimateComponent#31]
I have setup buttons on my dashboard, for Light, Health, Sleep. The Light and Sleep work fine,however Health does not, it returns to it's previous setting after a few seconds. It doesn't matter if the setting is previously on/off it can't be changed using the add on.

**Comment by RobHofmann** [comment]
does your AC support the health option?

Also please provide the details as requested in the template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Configuration**
Share your YAML here

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform:**
 - OS: [e.g. HASSIO, Hassbian]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 0.92.1]

**Additional context**
Add any other context about the problem here.

**Comment by dragonflyuk** [comment]
I'm not at home at the moment, so I'll do a proper report when there, the model is a CH-S18FTXE(WiFi)-NG which has the clean air setting, also referred to as health in the manual. 

Btw thanks for the very prompt replies.

**Comment by RobHofmann** [comment]
Also please turn on debug logging and share the debug logs.

**Comment by dragonflyuk** [comment]
**Describe the bug**
Setting Health via the addon is not working, correctly it resets after a few seconds. Setting the health option with the remote works and is displayed correctly by the addon

**To Reproduce**
Setup an input boolean as described below, try to activate it.

**Configuration**

> input_boolean:
>  living_room_ac_light:
>    name: "Living Room AC Light"
>  living_room_ac_health:
>    name: "Living Room AC Health"
>  living_room_ac_sleep:
>    name: "Living Room AC Sleep Mode"


>   - platform: gree
>     name: Living Room AC
>     host: 192.168.1.83
>     port: 7000
>     mac: 'f4:91:1e:48:22:04'
>     target_temp_step: 1
>     lights: input_boolean.living_room_ac_light
>     health: input_boolean.living_room_ac_health
>     sleep: input_boolean.living_room_ac_sleep



**Expected behavior**
I assume the setting should stick and stay selected.

**Platform:**

OS: HASSIO in Docker
Browser chrome
Version Hasso - 0.96.2, Gree Addon 2.0

**Comment by dragonflyuk** [comment]
Forgot this bit

>       - action: service
>         color: 'rgb(251, 210, 41)'
>         color_off: 'rgb(54, 95, 140)'
>         color_type: icon
>         entity: input_boolean.living_room_ac_health
>         icon: 'mdi:shield'
>         name: Health
>         service:
>           action: toggle
>           data:
>             entity_id: input_boolean.living_room_ac_health
>           domain: input_boolean
>         show_state: false
>         type: 'custom:button-card'
>

**Comment by dragonflyuk** [comment]
This is the relevant section of the log (I think), I have 4 units setup, so with debug on, logs are huge :-)

> 2019-07-23 17:32:49 INFO (MainThread) [custom_components.gree.climate] health_entity state changed |input_boolean.living_room_ac_health|<state input_boolean.living_room_ac_health=on; friendly_name=Living Room AC Health @ 2019-07-23T17:27:54.141962+03:00>|<state input_boolean.living_room_ac_health=off; friendly_name=Living Room AC Health @ 2019-07-23T17:32:49.093318+03:00>
> 2019-07-23 17:32:49 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/gree/climate.py", line 496, in _async_health_entity_state_changed
>     if not self._hvac_mode in (STATE_COOL, STATE_DRY):
> NameError: name 'STATE_COOL' is not defined
>

**Comment by RobHofmann** [comment]
Ah that last one helped. I just pushed a new version to master. I also created a new release which you can install through HACS. Let me know if this fixes your issue.

**Comment by dragonflyuk** [comment]
That seems to have fixed it, never realised you couldn't use the health mode in heat. I assume that is a restriction from the units.

**Comment by RobHofmann** [comment]
glad to hear! me neither, but i dont use the healthoption. :)

**Comment by sm4rk0** [comment]
@RobHofmann, Gree Viola owner here. I've just tested with IR remote and saw that health (ionizer - marked as a pine tree) and fresh air circulation (N/A in my model - marked as a house with in/out arrows) are selectable in all modes. What is not selectable is X-Fan option (keeps fan on after turning the AC off while in cooling/dehumidifying mode, so the internal unit can dry and prevent the growth of mold - marked as a 4-winged fan)
