### ISSUE TITLE
Set Horizontal Swing

### ISSUE THREAD

**Issue by lenisko** [RobHofmann/HomeAssistant-GreeClimateComponent#32]
**Is your feature request related to a problem? Please describe.**
Ability to set horizontal swing would be great.

**Describe the solution you'd like**
As far as I know, base `climate` doesn't have `set_horizontal_swing_mode` service.
Register new handler within component should be possible?

**Describe alternatives you've considered**
Add `set_horizontal_swing_mode` to hass `climate` base module, and support it within component.

**Additional context**
Constants: [here](https://github.com/arthurkrupa/gree-hvac-mqtt-bridge/blob/master/app/commandEnums.js#L89-L102) - not sure if they are same for all models though.
My model: ASH-13BIF2

**Comment by RobHofmann** [comment]
The theory is that the swing mode dropdown consists of all swing mode options. But this will mean you get HORIZONTAL_SWING_MODES * VERTICAL_SWING_MODES number of options in that list. It's possible, but i'm not positive yet this should be the solution.

As far as i know, adding new features and dropdowns to the platform is not possible. Correct me if i'm wrong.

Source: https://developers.home-assistant.io/docs/en/entity_climate.html

**Comment by lenisko** [comment]
Using one dropdown for both vertical and horizontal modes would be bad that's for sure.

That's why I was rather thinking about ability to call it via services (as we could create standalone dropdown using that) so far asked on discord if there's a chance to do that.
If that's not possible PR to `climate` module might be only solution.

**Comment by RobHofmann** [comment]
I doubt such PR will be accepted though. They just rethought the whole climate component. If you look at the documentation it clearly shows that you should set all the swing modes through 1 property.

**Comment by lenisko** [comment]
So there's one option, to register new service call for component. [Apparently it's possible.](https://developers.home-assistant.io/docs/en/dev_101_services.html)

**Comment by lenisko** [comment]
For now I'm leaving PR https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/pull/34 it's not yet finished, as registering a service needs finish touch. If you'll get some time please take a look at it @RobHofmann

**Comment by RobHofmann** [comment]
Hi, i'm looking into your PR. I've tried to get something working. At least for it to show the service, but the service doesnt pop up in the dev tools.

When I try to manually call the service i get this:
```
Failed to call service climate/set_horizontal_swing_mode. Service not found.
```

Am I doing something wrong?

Also: where is the service.yaml placed? next to the climate.py?

**Comment by lenisko** [comment]
Service is not injected yet, I didn't had a time to add it. Afaik it should be placed next to `climate.py` [(example)](https://github.com/TomerFi/home-assistant-custom-components/tree/master/switcher_aio/custom_components/switcher_aio)

**Comment by RobHofmann** [comment]
Also i'm still wondering how this will integrate into the frontend. I doubt we can modify the existing climate frontend component. We'd probably have to build something ourselves.

**Comment by RobHofmann** [comment]
Closing this for now as this is not supported by Home Assistant (yet).

**Comment by vampywiz17** [comment]
@RobHofmann 

Hello there,

If i see now home assistant support horizontal swing right?

https://developers.home-assistant.io/docs/core/entity/climate/#swing-modes

possible to re-investigate this?

**Comment by lenisko** [comment]
Hey @RobHofmann ! as it's already supported by HASS could you re-open issue?

**Comment by XenorPLxx** [comment]
Has anyone managed to implement this? I've tried to go through the code myself, but I'm not quite following how it works.

**Comment by RobHofmann** [comment]
I tried the default Gree component this week. The default Home Assistant Gree component has this feature. It allows you to swing both, vertical, horizontal or none. It however doesn't support any fixed positions.

**Comment by vampywiz17** [comment]
Hello @RobHofmann 

What do you think, it possible to add horizontal swing to your integration? (first time it enough that only the swing )

**Comment by RobHofmann** [comment]
> Hello @RobHofmann
> 
> What do you think, it possible to add horizontal swing to your integration? (first time it enough that only the swing )

I dont have any doubt it should be possible. Feel free to make a PR :).

**Comment by vampywiz17** [comment]
@RobHofmann 

I'm not a programmer, unfortunatelly, so i do a "workaround" in node-red.

![image](https://user-images.githubusercontent.com/14281430/123791878-43668c00-d8e0-11eb-88df-a6435c5cbeb1.png)

**Comment by XenorPLxx** [comment]
@vampywiz17 wow I didn't know there's Gree integration for node-red, it is a usable workaround, it even has its own dashboard example. Thanks! :)

**Comment by bekon16** [comment]
Hi,
Since horizontal swing is supported by climate I can dump and decode correct JSON for every position from left to right - but I don't have developer skills to implement this into this plugin.

Are those JSON's even required to add this feature (horizontal fixed swing mode) into this integration?

**Comment by vampywiz17** [comment]
@bekon16 

It also help, i think. But also no programming knowledge...

https://github.com/inwaar/node-red-contrib-gree-hvac

**Comment by bekon16** [comment]
So, here we go all requests and answers decoded.

Request 1:
`{
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    2
  ],
  "t": "cmd"
}
`
Request 2:
`{
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    3
  ],
  "t": "cmd"
}
`

Request 3:
`{
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    4
  ],
  "t": "cmd"
}
`
Request 4:
`{
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    5
  ],
  "t": "cmd"
}
`
Request 5:
`{
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    6
  ],
  "t": "cmd"
}
`
Answer 1:
`{
  "t": "res",
  "mac": "xxxxx",
  "r": 200,
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    2
  ],
  "val": [
    2
  ]
}
`
Answer 2:
`{
  "t": "res",
  "mac": "xxxxx",
  "r": 200,
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    3
  ],
  "val": [
    3
  ]
}
`
Answer 3:
`{
  "t": "res",
  "mac": "xxxxx",
  "r": 200,
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    4
  ],
  "val": [
    4
  ]
}
`
Answer 4:
`{
  "t": "res",
  "mac": "xxxxx",
  "r": 200,
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    5
  ],
  "val": [
    5
  ]
}
`
Answer 5:
`{
  "t": "res",
  "mac": "xxxxx",
  "r": 200,
  "opt": [
    "SwingLfRig"
  ],
  "p": [
    6
  ],
  "val": [
    6
  ]
}
`

**Comment by bekon16** [comment]
Hi,
Is it possible to at least add function to read current position for horizontal settings?
I can change:
['SwUpDn']]
to
['SwingLfRig']]
But i need both vertical and horizontal not only horizontal.

Can not managed it by myself.

**Comment by sthevenp** [comment]
Dear All,

Is there any change to get it integrated in one of the upcoming release?
It would be great to be part of it and not use another Node-Red integration for the horizontal swing settings.

Thanks for all the great work you've made on the Gree Climate integration!

**Comment by RobHofmann** [comment]
This is supported in the latest version :)
