### ISSUE TITLE
invalid configuration

### ISSUE THREAD

**Issue by wjketting** [RobHofmann/HomeAssistant-GreeClimateComponent#4]
As a relative newb related to ha and custom components, after installing arthurkrupa's gree mqtt bridge I was inquisitive to try this greeclimatecomponent.

Installed the custom component in custom_components/climate folder.
Followed the steps 1, 2 and 3 as described in the component installation remarks but when validating the configuration I got below mentioned error message.
![afbeelding](https://user-images.githubusercontent.com/46381645/50702249-a26d2200-1050-11e9-9598-a5cb4f15370d.png)
Any idea what I'm doing wrong?

To be complete, here's a view of the folders and files of my system:
![afbeelding](https://user-images.githubusercontent.com/46381645/50702454-48b92780-1051-11e9-885d-f916f8c07168.png)
Climate.yaml:
![afbeelding](https://user-images.githubusercontent.com/46381645/50702604-ae0d1880-1051-11e9-8bd1-991a7a075cf0.png)
Also tried entering the platform directly in configuration.yaml (same error message):
![afbeelding](https://user-images.githubusercontent.com/46381645/50702838-6dfa6580-1052-11e9-9e93-9e5f2a6a08ac.png)

**Comment by RobHofmann** [comment]
This should be fixed now. Please let me know if you encounter any issues with this.

Also this component does not use MQTT. I simply didnt update it for the newer HA versions yet :)
