### ISSUE TITLE
Is the AC operating?

### ISSUE THREAD

**Issue by wacher74** [RobHofmann/HomeAssistant-GreeClimateComponent#43]
I can't detect if my AC were operating.
Powered on but it is blowing heat or just standing by?

I'd like to start a fan when AC start working. 
I'd like to stop a fan 10 minutes after AC stop working.

**Comment by RobHofmann** [comment]
Hi! You should be able to do this with an automation using a timer and the services from this component.

The status is visible through the Home Assistant portal and (at least on my model) on the screen of the AC itself.

**Comment by wacher74** [comment]
It seems my AC don't provide this information. 
Neither in Gree+ app nor on its display is this information.
Could you check please that your status in which status field is? (I mean acOptions Pow, Mod, etc. Is there more?)

**Comment by RobHofmann** [comment]
`   '{' + '"opt":["Pow","Mod","SetTem","WdSpd","Air","Blo","Health","SwhSlp","Lig","SwingLfRig","SwUpDn","Quiet","Tur","StHt","TemUn","HeatCoolType","TemRec","SvSt"],"p":[{Pow},{Mod},{SetTem},{WdSpd},{Air},{Blo},{Health},{SwhSlp},{Lig},{SwingLfRig},{SwUpDn},{Quiet},{Tur},{StHt},{TemUn},{HeatCoolType},{TemRec},{SvSt}],"t":"cmd"'.format(**self._acOptions) + '}'
`

This is what you mean? If you want to know you can turn on Debug logging for this component. It will output all the values to homeassistant.log.

**Comment by wacher74** [comment]
Yes, thank you.
I checked the log file already but I don't see any trace of idle/working status :(
Maybe I should apply a mini temperature sensor in front of AC to detect the hot (or cold) airflow :)

**Comment by RobHofmann** [comment]
Yeah. I still dont really understand what you mean by working status. My HVAC is working when the status isnt "Off". So thats how I check. I dont check on temperatures. The HVAC itself makes sure to work hard when it heeds to heat/cool or idle if the temperature is about right.

Im closing this one. Please feel free to reopen if you have more input/questions.

**Comment by wacher74** [comment]
When I say "off", I mean the A/C is powered off.
When I say "idle", I mean the A/C is powered on but it does nothing.
When I say "working", I mean the A/C is blow hot air. 

I would like to detect when de A/C do its job: it is heating or cooling. I would like detect when A/C "work hard" :) Because I have to start an other fan if the A/C blow hot air.

Now I can detect this just with an external temperature sensor (installed in front of AC device) because the A/C does not provide the information. I don't want reopen the ticket I wrote these just for records.

**Comment by RobHofmann** [comment]
Right, then you'd need an external monitor indeed. Afaik the Gree protocol has no support for this (read: the device does not support this)
