### ISSUE TITLE
problem identifying all ACs

### ISSUE THREAD

**Issue by KarelsonPL** [RobHofmann/HomeAssistant-GreeClimateComponent#47]
Hi,

I am receiving the following err when HA loads and only 1 AC is up and recognized:

Error while setting up platform gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 112, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 155, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 227, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 210, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

Any ideas?

**Comment by RobHofmann** [comment]
It gives a timeout. That simply says that your Home Assistant setup is unable to reach the target you have specified.

Please share your config.

**Comment by akkovachev** [comment]
Hello installed the component i managed to make it work for one of my AC's but i get the same error as the person above when i added my second ac

climate.yaml
`- platform: gree
  name: "First AC"
  host: 192.168.0.101
  port: 7000
  mac: 'F4:91:1E:7E:6D:60'
  target_temp_step: 1
  encryption_key: 3Gh6Jk9Mn2Pq5St8
  
- platform: gree
  name: Living Room AC
  host: 192.168.0.105
  port: 7000
  mac: 'A0:9D:C1:DD:91:74'
  target_temp_step: 1
  encryption_key: St0Vw3Yz6Bc9Ef2H`

I am using the encryption key as i already have my ac's set to use the Gree App for android. Idk if my AC is exactly compatible but it should be as it came with a Wifi Option and i can control it without an issue using the Gree App. If more details are needed let will be happy to provide them.

**Comment by PLTorrent** [comment]
Try turning off the 1st AC (disconnect the power cable) and see if now the app will talk to the second one. If yes then turn on the first one and see if the issue reappears. I got some theory but it's just a wild guess.

**Comment by RobHofmann** [comment]
Also if the above suggestion doesn't work, try to disable the config for 1 ac (lets try to get 1 working first). And also remove the encryption_key for now to test if that works (i dont have a setup for testing the encryption_key here).

Let me know if that does anything.

Also do a `telnet 192.168.0.105 7000` from your PC and post results.

**Comment by RobHofmann** [comment]
Please take a look at #40 

Closing this for now. Feel free to re-open if the issue still occurs.
