### ISSUE TITLE
Row 302

### ISSUE THREAD

**Issue by claudiosala80** [RobHofmann/HomeAssistant-GreeClimateComponent#48]
I was reviewing the script for the sleep issue (see other post).
It seems there is an error in row 302

Could you please check?

**Comment by wjketting** [comment]
302 seems ok to me:
`                    self.hass.states.async_set(self._xfan_entity_id, self._current_xfan, attr)`
maybe you ment 303?
`        _LOGGER.info('HA health option set according to HVAC state to: ' + str(self._current_health))`
303 should be:
`        _LOGGER.info('HA xfan option set according to HVAC state to: ' + str(self._current_xfan))`
copy/paste error, no effect on communication with the airco though.

**Comment by claudiosala80** [comment]
Yes basically there is a wrong variable
I simply see it in the code, not see any error

Il mer 25 dic 2019, 12:29 Wolter <notifications@github.com> ha scritto:

**Comment by RobHofmann** [comment]
Should be good now. Thanks for the report.
