### ISSUE TITLE
Can not find climate platform

### ISSUE THREAD

**Issue by blazkom** [RobHofmann/HomeAssistant-GreeClimateComponent#5]
I run this addon on Hassio but i always get response can not find platform climate

When i look at traceback i get this response

`Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 92, in get_component module = importlib.import_module(path) File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "&lt;frozen importlib._bootstrap&gt;", line 994, in _gcd_import File "&lt;frozen importlib._bootstrap&gt;", line 971, in _find_and_load File "&lt;frozen importlib._bootstrap&gt;", line 955, in _find_and_load_unlocked File "&lt;frozen importlib._bootstrap&gt;", line 665, in _load_unlocked File "&lt;frozen importlib._bootstrap_external&gt;", line 678, in exec_module File "&lt;frozen importlib._bootstrap&gt;", line 219, in _call_with_frames_removed File "/config/custom_components/climate/gree.py", line 21, in &lt;module&gt; from homeassistant.helpers.restore_state import async_get_last_state ImportError: cannot import name 'async_get_last_state'`

**Comment by RobHofmann** [comment]
This should be fixed now. Please let me know if you encounter any issues with this.
