### ISSUE TITLE
 Add support cooper hunter ac.

### ISSUE THREAD

**Issue by T-REX-XP** [RobHofmann/HomeAssistant-GreeClimateComponent#55]
Hi, could you please to add support of cooper hunter AC? 

Here is my repo with worked controller on node.js platform. Can you port It to the native python code?
https://github.com/T-REX-XP/cooper_hunter-hvac-mqtt-bridge

I really want to see native support of this AC for HA.

Thanks in advance.

**Comment by RobHofmann** [comment]
I'm not sure what you mean.

I own 2 Cooper Hunter AC's myself and I built this component specifically to support those.

What isn't working for you?

**Comment by T-REX-XP** [comment]
Yes, Unfortunately, your component is not working for me. I have got AC C&H Nordic Evo 2(Ch-s09ftn-e2wf), with different discovery port (12414) and a different communication port(12416)

All sources are presented in my repository.

Thanks

**Comment by RobHofmann** [comment]
can you share what kind of errors you receive (if any)? maybe share logs with debug as well.

**Comment by T-REX-XP** [comment]
Hi. Thanks for the support. 
As I understand, my AC has a different port and has UDP proto instead of TCP

Please find below the part of the code of the connect method.

```
/**
     * Initialize connection
     * @param {string} address - IP/host address 
     */
    _connectToDevice(address) {
        try {
            socket.bind(() => {
                const bufView = new Buffer(9);
                bufView[0] = 0xAA;
                bufView[1] = 0xAA;
                bufView[2] = 0x06;
                bufView[3] = 0x02;
                bufView[4] = 0xFF;
                bufView[5] = 0xFF;
                bufView[6] = 0xFF;
                bufView[7] = 0x00;
                bufView[8] = 0x59;

                socket.setBroadcast(true);
                socket.send(bufView, 0, bufView.length, this.defaultPort, address);

                console.log('[UDP] Connected to device at %s', address);
            });
        } catch (err) {
            const timeout = 60;

            console.log('[UDP] Unable to connect (' + err.message + '). Retrying in ' + timeout + 's...');
            setTimeout(() => {
                this._connectToDevice(address);
            }, timeout * 1000);
        }
    }
```

**Comment by RobHofmann** [comment]
Hmm this seems a bit different yes.

Feel free to make a PR with support for this AC.

**Comment by RobHofmann** [comment]
Closing this since different protocol implementations are not supported by this integration. Feel free to make a PR adding support for your model.
