### ISSUE TITLE
I-Feel function implementation

### ISSUE THREAD

**Issue by Machaeon** [RobHofmann/HomeAssistant-GreeClimateComponent#57]
Hello. Is it possible to implement I-Feel function to feed HVAC with temperature value from external sensor?
Thank you.

**Comment by PLTorrent** [comment]
Hi,

Not needed as this can be done/ managed via home assistant automation. The idea of climate control tab in home assistant is that you also connect a temp sensor to it. I for example use a temp sensor from my Xiaomi Air Purifier.

Best regards.

**Comment by Machaeon** [comment]
Hello! So AC unit use external sensor to control temperature instead of internal?

**Comment by PLTorrent** [comment]
If you run it on auto it will use internal. If you automate it via home assistant it can use external. The Ifeel function uses a sensor in infrared remote to report the temperature in the remotes location. There is no ifeel function in the mobile phone app. This component uses the api of the original mobile app hence it is not possible to use the ifeel function in the home assistant using the sensor from remote.

Hope this clears any doubt.
