### ISSUE TITLE
Encryption key on iOS devices

### ISSUE THREAD

**Issue by cmroche** [RobHofmann/HomeAssistant-GreeClimateComponent#69]
Just a bit of information to help out other users.

I was able to recover the encryption key by using a tool called "imazing" https://imazing.com/ which allows you to backup your app data locally, and then explore the backup for the "Gree+" app. The .sqlitefs file can then be copied to your filesystem, and inspected from there.

![image](https://user-images.githubusercontent.com/1007595/85418180-75f7df00-b53e-11ea-8886-656dc751a434.png)

You can extract the publickey from the "deviceTable" table.

![image](https://user-images.githubusercontent.com/1007595/85418563-eacb1900-b53e-11ea-85cc-34bbb84ed7b9.png)

**Comment by PLTorrent** [comment]
Please check this: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/64#issuecomment-655345702
