### ISSUE TITLE
Question: HA goes into to SAFE MODE

### ISSUE THREAD

**Issue by dudster83** [RobHofmann/HomeAssistant-GreeClimateComponent#70]
Guess something is wrong with my configuration
Am running HA 0.111.3 on a docker
I'd created the climate.yaml file

`platform: gree
  name: Office
  host: 192.168.192.21
  port: 7000
  mac: 'xx:xx:xx:xx:xx'
  target_temp_step: 1
  encryption_key: xxxxxxxxxxxxxxxxxxx
  uid: xxxxxxxxxxx
  lights: input_boolean.first_ac_lights
  xfan: input_boolean.first_ac_xfan
`
in configuration.yaml i'd added
`climate: !include climate.yaml
`

there's mapping from the climate.yaml file into the /config folder inside the container, but i'm getting

`pi@raspberrypi:~/ha $ cat home-assistant.log
2020-06-27 20:08:40 ERROR (SyncWorker_1) [homeassistant.util.yaml.loader] mapping values are not allowed here
  in "/config/climate.yaml", line 2, column 7
2020-06-27 20:08:40 ERROR (MainThread) [homeassistant.bootstrap] Failed to parse configuration.yaml: mapping values are not allowed here
  in "/config/climate.yaml", line 2, column 7. Activating safe mode
`

any help will be much appreciated
David

**Comment by dudster83** [comment]
you can close it, beginners mistake

**Comment by sm4rk0** [comment]
You can also close it.

**Comment by bakadave** [comment]
> you can close it, beginners mistake

@dudster83 please elaborate for other newbies next time :)
