### ISSUE TITLE
Climate GreeAC to provide unique_id

### ISSUE THREAD

**Issue by raoulx24** [RobHofmann/HomeAssistant-GreeClimateComponent#76]
**Is your feature request related to a problem? Please describe.**
I needed to be able to use the climate greeac as enitites in ha

**Describe the solution you'd like**
I added the following in climate.py:

```python
 __init__(self
[... ]
self._unique_id = re.sub('[^0-9a-zA-Z]+', '_', name).lower()
```
 
down, below, as the last property:

```python
    @property
    def unique_id(self):
        # Return unique_id
        return self._unique_id
```

 As far as I could see, all the other entity_ids are created by ha the same way, so this should work. In my case it is working :)

Enjoy and thank you for this great ha custom component

**Comment by RobHofmann** [comment]
Could you turn this into a pullrequest or elaborate a little more? I'm interested in what you are doing, but I don't fully understand it yet.

**Comment by raoulx24** [comment]
Will do in the following days. I am caught up with some work. :)

**Comment by xuefer** [comment]
since mac is unique and recommended by ha document, why not use mac for unique id?
