### ISSUE TITLE
Scavenging Function

### ISSUE THREAD

**Issue by poisondima** [RobHofmann/HomeAssistant-GreeClimateComponent#78]
Thank you so much for the work done, I connected Gree Muse R32 Air Conditioner (Wi-Fi) GWH09AFB-K6DNA1A via HACS without any problems!
I use the "health" function (looks like a tree), but there is also Scavenging Function, is it possible to add this function?

Scavenging Function
This mode allows the indoor unit to extract air from the room. if the room is very hot, you can enable this to cool the room down very quickly. It can also be used to remove odors from the room quickly. Text from the manual:
![Аннотация 2020-08-05 173706](https://user-images.githubusercontent.com/39500249/89426180-8b1d7b80-d742-11ea-9185-47e32efed789.png)
In a mobile application, it looks like this:
![photo_2020-08-05_17-47-33](https://user-images.githubusercontent.com/39500249/89427917-7641e780-d744-11ea-9bfe-9b472d945f4f.jpg)
Thank.

**Comment by RobHofmann** [comment]
It's going to be pretty much impossible for me to implement this, since i have no testing hardware. Feel free to implement this yourself and make a pullrequest on this repo :).

**Comment by TheTimeWalker** [comment]
I've got a hardware with this feature. If I find the time I could try to look into this

**Comment by TheTimeWalker** [comment]
I have looked into this and the component is already getting the status of the scavenger mode as "Air". The only thing that is needed is adding a input_boolean to HA
