### ISSUE TITLE
Localization strings

### ISSUE THREAD

**Issue by ardeus-ua** [RobHofmann/HomeAssistant-GreeClimateComponent#8]
Hi, is this possible to replace state attributes to localized strings, so it will appear with translated strings? Thank you

**Comment by RobHofmann** [comment]
https://developers.home-assistant.io/docs/en/internationalization_custom_component_localization.html

Seems to be possible :). I don't have the time to find this out right now, but don't hesitate to make PR enabling this 👍

**Comment by ardeus-ua** [comment]
Replacing the imports and strings to STATE_ON, STATE_OFF (climate.const) will use already translated strings from Home Assistant

**Comment by RobHofmann** [comment]
Thanks for your PR. I'll leave this one open until everything has been replaced by localized strings.

**Comment by RobHofmann** [comment]
I just looked into this. From what I can find, we can't create custom translations for custom strings. We can override the translations for the supported fields with custom values, but we can not create custom strings with translations.

Closing this for now. Feel free to reopen when you have more insights.
