### ISSUE TITLE
Climate displays Celcius temperature, default HA unit set to Fahrenheit

### ISSUE THREAD

**Issue by hgelpke** [RobHofmann/HomeAssistant-GreeClimateComponent#84]
The component despite slowing the correct temp in the app, shows the incorrect temp in HA.

Is there a way to to change the unit of measure?

![image](https://user-images.githubusercontent.com/10578840/92342195-f1b0f480-f074-11ea-93ef-7ec3aa8403be.png)

![image](https://user-images.githubusercontent.com/10578840/92342239-1a38ee80-f075-11ea-9c37-cc69024aab27.png)

**Comment by RobHofmann** [comment]
This is set by the homeassistant setting. Go to Configuration --> General and check what the setting is there. It should be set to Metric.

**Comment by hgelpke** [comment]
Thank you. I had units in Config.yaml but it didn't translate. Once I
commented those out and used the UI it was perfect.

**Comment by tjdavisbz** [comment]
I am having the same issue even though it is set to Fahrenheit in the HA config and I removed the setting in Configuration.yaml.   Anything else I can check?   It does show the Fahrenheit symbol but the temperature is in Celcius.   So right now I have it set to 82 Fahrenheit and that is what displays on the AC screen but it says 28 Fahrenheit in HA.

**Comment by RobHofmann** [comment]
I'd have to redirect you to the Home Assistant forums, since I don't control these settings from the plugin.

Closing this for now.
