### ISSUE TITLE
Dummy server for gree AC

### ISSUE THREAD

**Issue by Hagakurje** [RobHofmann/HomeAssistant-GreeClimateComponent#88]
There is a problem with AC, when internet is off (or gree servers is down). It depends on wifi module software, without internet AC reconnects to wifi every few seconds. More details in this bug - https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/75

I fount great repository - dummy server for gree AC. https://github.com/Hagakurje/GreeAC-DummyServer
Dummy server can communicate with AC and answer like real server! All you need is redirect all requests from eu.dis.gree.com to this server.

Maybe it is possible to implement dummy server in your component?

**Comment by RobHofmann** [comment]
Feel free to make a pullrequest with this feature.

My AC's dont have this issue. I blocked my AC's entirely from the internet (they are in a special range within my network). They work perfectly fine from Home Assistant.

**Comment by RobHofmann** [comment]
Closing this for now.
