### ISSUE TITLE
explanation of the option parameters 可选参数名的真正意思

### ISSUE THREAD

**Issue by hemingfei** [RobHofmann/HomeAssistant-GreeClimateComponent#90]
I am a little confused about the parameters meaning.

example we have is below:
_______________________________________
- platform: gree
  name: First AC
  host: <ip of your first AC>
  port: 7000
  mac: '<mac address of your first AC. NOTE: Format can be XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX depending on your model>'
  target_temp_step: 1
  encryption_key: <OPTIONAL: custom encryption key>
  uid: <some kind of device identifier. NOTE: for some devices this is optional>
  temp_sensor: <entity id of the EXTERNAL temperature sensor. For example: sensor.bedroom_temperature. NOTE: this attaches an external temperature sensor to your AC. Gree unfortunately doesnt support a "current temperature" on its own.>
  lights: <OPTIONAL: input_boolean to switch AC lights mode on/off. For example: input_boolean.first_ac_lights>
  xfan: <OPTIONAL: input_boolean to switch AC xfan mode on/off. For example: input_boolean.first_ac_xfan>
  health: <OPTIONAL: input_boolean used to switch the Health option on/off of your first AC. For example: input_boolean.first_ac_health>
  sleep: <OPTIONAL: input_boolean to switch AC sleep mode on/off. For example: input_boolean.first_ac_sleep>
  powersave: <OPTIONAL: input_boolean to switch AC powersave mode on/off. For example: input_boolean.first_ac_powersave>
  eightdegheat: <OPTIONAL: input_boolean used to switch 8 degree heating on/off on your first AC>
  air: <OPTIONAL: input_boolean used to switch air/scavenging on/off on your first AC>
_______________________________________

whats the meaning of xfan, eightdegheat, air?

I guess:  xFan is let the fan move and stop.  eightdegheat is the fastest wind speed on and off.  air is the clean mode?

in another words in chinese. 这些参数是什么意思， xfan是扫风么，eightdegheat是强劲么， air是清洁么。

by the way, is there a parameter that can control the wind speed?

**Comment by RobHofmann** [comment]
Some of the parameters are explained by @wjketting here:
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/pull/16#issuecomment-496016366

If you initially want to setup this component, this should be enough:
```yaml
platform: gree
name: First AC
host:
port: 7000
mac: ''
target_temp_step: 1
```

After adding the component, you will be able to control the temperature, windspeed, mode & fan direction of the AC.

Let me know if you need any more help.

**Comment by hemingfei** [comment]
thanks mate. I found the windspeed and fan direction.

I still confused about the  xfan, eightdegheat and air. whats the explanation.

In my home. 4 gree ac is OK to connected the home assistant.   another 1 gree ac is still cannot, im still trying to find the problem. here is the link of the ac https://item.jd.com/71568246114.html   it can control by the app gree+

**Comment by RobHofmann** [comment]
XFan:
It seems that the XFan option (if your gree AC supports it) "dries" the AC after being used. This is to mitigate the nasty smells you can otherwise get.

Air (Scavenging Function):
This mode allows the indoor unit to extract air from the room. if the room is very hot, you can enable this to cool the room down very quickly. It can also be used to remove odors from the room quickly. Text from the manual:
![Аннотация 2020-08-05 173706](https://user-images.githubusercontent.com/39500249/89426180-8b1d7b80-d742-11ea-9185-47e32efed789.png)
Source: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/78

8C Heat function:
This one I forgot and cannot find back. Maybe @PLTorrent or @wacher74 can say something about this?

Also note that

**Comment by wacher74** [comment]
"8° Celsius mode, this feature maintains the room temperature steadily at 8°C and prevents the room from freezing by activating the heating operation automatically when nobody is at home over a longer period during severe winter."

**Comment by hemingfei** [comment]
> "8° Celsius mode, this feature maintains the room temperature steadily at 8°C and prevents the room from freezing by activating the heating operation automatically when nobody is at home over a longer period during severe winter."

8°C? your AC can set 8°C ?  mine the lowest is 16°C

**Comment by wacher74** [comment]
This is not a manual temperature settings, but "activating the heating operation **_automatically_**"

**Comment by RobHofmann** [comment]
Thanks @wacher74 for clearing it up.

I updated the README to explain the features to my best ability.
