### ISSUE TITLE
Gree current temperature uses

### ISSUE THREAD

**Issue by drynish** [RobHofmann/HomeAssistant-GreeClimateComponent#93]
**Is your feature request related to a problem? Please describe.**
What I want to know is if I can achieve the following:

Having a smart thermostat located in a central position in my house as a sensor which will provide the current temperature and the gree hvac would base it's decision on that thermostat.

I was able to transfer the info from the thermostat to a template sensor which was included in my gree climate configuration as the temp_sensor. Everything is working well, however I'm not sure it's based on that temperature.

I'm pretty sure that right now the current_temperature is not used by the gree hvac.

**Describe the solution you'd like**
Gree HVAC will chose action based on the temperature coming from the thermostat.

**Describe alternatives you've considered**
Gree HVAC also supports I FEEL which is based on the gree actual remote location. Maybe we could submit info that way too...

**Comment by RobHofmann** [comment]
As far as my knowledge goes, the HVAC is just outputting air with the temperature you tell it to be. There is no temperature sensors involved (correct me if i'm wrong).

For example: my hvac doesnt have a sensor and therefore doesnt give a "current temperature" back in the API. Not sure if this is the same for all Gree HVACs.

I suggest to use HASS automations for the goal you are trying to achieve.

**Comment by lukaszliniewicz** [comment]
This is something I've been wondering about as well. I'm using the native HA Gree integration (Gree Climate) and the unit is reporting current temperature (it's basically useless for heating, it always gets too high too soon, so I have a crude setup setting it on/off and setting the temp to 30C when on controlled by an external sensor). It would be beneficial for efficiency, I suppose, to let the unit adjust it's operation based on the external sensor directly. Is this how the implementation in this integration works?
