### ISSUE TITLE
Upgrading HA core to 2021.1.3 breaks everything 

### ISSUE THREAD

**Issue by marcomow** [RobHofmann/HomeAssistant-GreeClimateComponent#94]
**Describe the bug**
As requested by HA developer to upgrade ASAP for security reasons, I upgraded and this addon is not working anymore

**Platform:**
 - OS: hassio
 - Browser chrome

**Logs**
Logger: homeassistant.components.climate
Source: custom_components/gree/climate.py:230
Integration: Climate (documentation, issues)
First occurred: 0:38:03 (1 occurrences)
Last logged: 0:38:03

Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 118, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, air_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 165, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 247, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 230, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

**Comment by drynish** [comment]
Just to let you know that this version is working with the 2021.1.3. It seems to be something with the key as if it was not the same?

**Comment by marcomow** [comment]
From my side I didn't change anything, can you please suggest what to do?

**Comment by RobHofmann** [comment]
Nothing changed in the API's. I'm on 2013.1.3 and it works exactly like before.

Please check your network configuration.

PS. Try a search for the "clientSock.recvfrom(64000)" more people have seen this issue. This not something I can fix from a code perspective. This usually revolves around a network misconfiguration.

**Comment by marcomow** [comment]
Seems like you said, thanks for the reply!
