### ISSUE TITLE
Update the integration on HACS?

### ISSUE THREAD

**Issue by Sjorsa** [RobHofmann/HomeAssistant-GreeClimateComponent#98]
I added the integration via HACS but I get ```No 'version' key in the manifest file for custom integration 'gree'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'gree'``` in the HA logs. I see this has already been resolved in an issue, has this not been pushed to HACS yet?

**Comment by RobHofmann** [comment]
Thanks for the reminder. I indeed forgot to do this. 2.2.1 is released now :).
